### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bewisesh91** [APD-Kim/node.jsAPI#1]
필수 요구 사항: 프로젝트 관리
- [x] 1. `.env` 파일을 이용해서 민감한 정보(DB 계정 정보, API Key 등)를 관리합니다.
- [x] 2. `.gitignore` 파일을 생성하여 `.env` 파일과 `node_modules` 폴더가 Github에 올라가지 않도록 설정합니다.
- [x] 3. `.prettierrc` 파일을 생성하여 일정한 코드 포맷팅을 유지할 수 있도록 설정합니다.

-----
필수 요구 사항: API 구현하기
 1. 상품 작성 API
- [x] 상품명, 작성 내용, 작성자명, 비밀번호를 **request**에서 전달 받기
- [x] 상품은 두 가지 상태, **판매 중(`FOR_SALE`)및 판매 완료(`SOLD_OUT`)** 를 가질 수 있습니다.
- [x] 상품 등록 시 기본 상태는 **판매 중(`FOR_SALE`)** 입니다.
2. 상품 목록 조회 API
- [x] 상품명, 작성자명, 상품 상태, 작성 날짜 조회하기
- [x] 상품 목록은 작성 날짜를 기준으로 **내림차순(최신순)** 정렬하기
3. 상품 상세 조회 API
- [x] 상품명, 작성 내용, 작성자명, 상품 상태, 작성 날짜 조회하기
4. 상품 정보 수정 API
- [x] 상품명, 작성 내용, 상품 상태, 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **수정**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기
5. 상품 삭제 API
- [x] 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **삭제**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기

-----
필수 요구 사항
- [x] AWS EC2 배포

-----

필수 요구 사항을 모두 잘 구현하신 것 같습니다. 
bcrypt를 통해서 비밀번호를 암호화 한 것도 최고입니다.
사용자의 입력과 DB에 저장된 값을 단순 비교하는 식으로 구현하신 분들이 많았는데 잘하셨습니다.

일부 코드에 대해 궁금한 사항이 있어 적어봅니다.
우선, schema에서 isSale을 사용하고 있는데 type은 string인데 boolean 형식으로 간주하는 것 같은 느낌을 받았습니다.
타입과 의도가 명시적으로 동일하면 좋을 것 같은데 일부러 이렇게 하신 것인지 궁금합니다!

추가적으로 route 주소 하나에 여러 메서드들을 작성하고 있는데, 
사실 이렇게 적는 분들도 있지만 개인적으로는 명시적으로 route 주소를 메서드 마다 표기하는 것이 좋다고 생각하거든요!
혹시 이렇게 작성하신 재연님의 구현 의도가 궁금합니다!

첫 번째 개인 과제인데 엄청 잘하셨습니다.
2차 과제도 멋지게 해내보아요! 👍

**Comment by APD-Kim** [comment]
isSale에 대해서는 사실 맨처음에는 말씀하신것처럼 boolean값으로 판매중일땐 true, 판매중이지 않을때는 false로 하려고 했었는데, 생각해보니 boolean값으로 하게되면 두가지의 상태밖에 표현하지 못한다고 생각이 들어서 나중에 FOR_SALE처럼 string으로 변환을 했습니다. 그런데 이름을 바꾸는 것 까지는 생각하지 못했네요..

하나의 route주소에 여러개의 메소드를 작성한것은 최초에는 route주소마다 메서드를 표기해줬었는데, 구글링을 하다보니 공통되는 endpoint끼리는 하나의 route로 묶을 수 있다고 해서 한번 해봤습니다.. 근데 생각보다 가독성이 별로 좋지는 않아서 아마 다음부터는 하지 않을 것 같습니다 ㅠㅠ

피드백 정말 감사드리고 혹시라도 더 고쳐보면 좋을것 같은 부분이 있다면 말씀해주시면 감사하겠습니다!!
피드백 감사합니다~~
